{% set name = "zencfg" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zencfg-{{ version }}.tar.gz
  sha256: 937a2aec36332c20579c790200b51e77842bde6659a4a0077a385842d45b8155

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - pydantic

test:
  imports:
    - zencfg
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/JeanKossaifi/zencfg
  summary: The Zen way to configure your Python projects, deep learning and others
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
