{% set name = "zencfg" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/zencfg-{{ version }}.tar.gz
  sha256: 6444d176cbd936436ca4941672313b29ff331a8da187d2d5375f4ef8a5fb349a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - pydantic

test:
  imports:
    - zencfg
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/JeanKossaifi/zencfg
  summary: The Zen way to configure your Python projects, deep learning and others
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
